# Generated by Django 4.1.2 on 2022-10-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="profile_images"),
        ),
    ]
